name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Publish Plugin
        env:
          GRADLE_PUBLISH_KEY: ${{ vars.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        run: ./gradlew publishPlugins --no-daemon --stacktrace --no-configuration-cache

      - name: Create Git Tag
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          VERSION=$(cat VERSION)
          git tag -a v$VERSION -m "Release v$VERSION"
          git push origin v$VERSION
